### PR TITLE
Move the recipe to noarch and increment build number

### PR DESCRIPTION
**Pull request by xylar**
Removed c compiler because it doesn't look like it is used.

Updated the script to match the suggestion in the current example
recipe on conda-forge staged recipes.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@thebestnom, I noticed that this package could be simplified a little bit in the process of helping someone with a different recipe.  Feel free to ignore this PR if you like, just trying to help keep things tidy.

**Comment by xylar** [comment]
Also, I added myself as a maintainer, which seemed like the polite thing to do in the process but please feel free to remove me if you'd like to maintain this recipe on your own.

**Comment by thebestnom** [comment]
Im pretty sure that this package have a c and pyx component, and to my knowledge that means that it cant be a noarch, am I wrong?

**Comment by xylar** [comment]
Oh, sorry.  I missed that.  I'll close this, then.

**Comment by thebestnom** [comment]
Ok, thanks for trying to help!

**Pull request closed without merging**
